##
# Configure the server for the Django app
##
- include: 01_server.yml
- include: 02_git.yml
- include: 03_dependencies.yml
- include: 04_postgres.yml
- include: 05_migrations.yml
- include: 06_nginx.yml
- include: 07_gunicorn.yml
- include: 09_systemd.yml
