##
# This playbook deploys the whole app stack
##

- hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.9


- name: apply common configuration to server
  hosts: all
  user: deployer
  roles:
    - common

  

  