# Generated by Django 2.2.9 on 2020-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_onlinemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
