# Generated by Django 2.2.9 on 2020-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_onlinemeeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='platform',
            field=models.CharField(choices=[(1, 'Zoom'), (2, 'Skype')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
