# Generated by Django 2.2.9 on 2020-03-25 07:35

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_onlinemeeting_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'day']),
        ),
        migrations.AlterField(
            model_name='onlinemeeting',
            name='platform',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Skype', 'Skype')], max_length=10),
        ),
    ]
