# Generated by Django 2.2.9 on 2020-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_auto_20200325_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='day_number',
            field=models.IntegerField(null=True),
        ),
    ]
