# Generated by Django 2.2.9 on 2020-03-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_onlinemeeting_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemeeting',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinemeeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
