# Generated by Django 2.2.9 on 2020-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_auto_20200326_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemeeting',
            name='day',
            field=models.CharField(choices=[('All', 'All'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
    ]
