# Generated by Django 2.2.9 on 2020-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_auto_20200326_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinemeeting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='onlinemeeting',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
