# Generated by Django 2.2.9 on 2020-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_auto_20200405_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemeeting',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
