# Generated by Django 2.2.9 on 2020-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_auto_20200405_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='hearing',
            field=models.BooleanField(default=False),
        ),
    ]
