# Generated by Django 2.2.9 on 2020-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0011_onlinemeeting_hearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='time_band',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
