# Generated by Django 2.2.9 on 2020-06-29 19:52

from django.db import migrations
from datetime import time

def update_time_band(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    OnlineMeeting = apps.get_model('online', 'OnlineMeeting')
    for meeting in OnlineMeeting.objects.all():
        meeting_time = meeting.time
        
        if meeting_time > time(0, 0) and meeting_time <= time(12,0):
            meeting.time_band = 'morning'
        elif meeting_time > time(12,0) and meeting_time <= time(18,0):
            meeting.time_band = 'afternoon'
        else:
            meeting.time_band = 'evening'
        
        meeting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0012_onlinemeeting_time_band'),
    ]

    operations = [
        migrations.RunPython(update_time_band),
    ]
