# Generated by Django 2.2.18 on 2021-02-17 23:38

from django.db import migrations
from django.core import serializers

def migrate_online_meeting_data(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    MeetingDay = apps.get_model("meetings", "MeetingDay")
    OnlineMeeting = apps.get_model("online", "OnlineMeeting")

    online_meetings = OnlineMeeting.objects.all()
    for online_meeting in online_meetings:
        
        meeting=Meeting.objects.create(
            title=online_meeting.title,
            time=online_meeting.time,
            type="ONL",
            submission="Existing",
            online_link=online_meeting.link,
            description=online_meeting.description,
            notes = online_meeting.additional_comments,
            email = online_meeting.email or 'noemailgiven@aalondon.com',
            code = -1,
            hearing=online_meeting.hearing,
            wheelchair=False,
            types="")
     
        
        if online_meeting.day == "All":
            for day in  MeetingDay.objects.all():
                meeting.days.add(day)
        else:
            meeting_day = MeetingDay.objects.get(value=online_meeting.day)
            meeting.days.add(meeting_day)
        
        meeting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('online', '0013_auto_20200629_1952'),
    ]


    operations = [
        migrations.RunPython(migrate_online_meeting_data),
    ]
