# Generated by Django 2.2.6 on 2019-10-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
