# Generated by Django 2.2.6 on 2019-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20191030_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
