# Generated by Django 2.2.6 on 2019-11-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='day_rank',
            field=models.IntegerField(null=True),
        ),
    ]
