# Generated by Django 2.2.6 on 2019-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_intergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='detail',
            field=models.TextField(default='this will be overwritten'),
            preserve_default=False,
        ),
    ]
