# Generated by Django 2.2.6 on 2019-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_meeting_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='day_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='intergroup',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
