# Generated by Django 2.2.9 on 2020-02-03 07:50

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20191220_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'day', 'postcode']),
        ),
    ]
