# Generated by Django 2.2.9 on 2020-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meeting_time_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='covid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='address',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='day_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='intergroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_band',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
