# Generated by Django 2.2.9 on 2020-06-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20200619_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='covid_status',
            new_name='covid_open_status',
        ),
    ]
