# Generated by Django 2.2.9 on 2020-08-19 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_auto_20200619_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
