# Generated by Django 2.2.9 on 2020-08-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_auto_20200619_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.IntegerField(choices=[(0, 'Physical'), (1, 'Online'), (2, 'Hybrid')], default=0),
        ),
    ]
