# Generated by Django 2.2.16 on 2020-10-25 12:20

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_auto_20200819_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='conference_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=['title', 'day', 'postcode', 'time']),
        ),
    ]
