# Generated by Django 2.2.16 on 2020-10-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_auto_20201025_1659'),
        ('meetings', '0015_auto_20201025_1220'),
    ]

    operations = [
    ]
