# Generated by Django 2.2.18 on 2021-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0018_meeting_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingIntergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='email',
            field=models.EmailField(default='doesnotexist@aalondon.com', max_length=254),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='online_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='payment_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='submission',
            field=models.CharField(default='existing', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('F2F', 'Face To Face'), ('ONL', 'Online'), ('HYB', 'Hybrid')], default='F2F', max_length=3),
        ),
        migrations.AddField(
            model_name='meeting',
            name='what_three_words',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='days',
            field=models.ManyToManyField(related_name='meeting_days', to='meetings.MeetingDay'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sub_types',
            field=models.ManyToManyField(blank=True, to='meetings.MeetingSubType'),
        ),
    ]
