# Generated by Django 2.2.24 on 2021-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0025_meeting_xmas_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='xmas_closed',
            field=models.BooleanField(default=False),
        ),
    ]
