# Generated by Django 3.2.16 on 2022-12-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0026_meeting_xmas_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='covid_open_status',
        ),
    ]
