# Generated by Django 3.2.16 on 2023-02-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0028_rename_gso_opt_in_meeting_gso_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
