# Generated by Django 3.2.16 on 2022-12-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0028_meeting_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='payment_details',
            new_name='tradition_7_details',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='conference_url',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='hearing',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='types',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='wheelchair',
        ),
    ]
