# Generated by Django 3.2.16 on 2022-12-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0029_auto_20221227_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='intergroup_id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='postcode_prefix',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='intergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_intergroup', to='meetings.meetingintergroup'),
        ),
    ]
