# Generated by Django 3.2.16 on 2023-08-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0029_meeting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='note_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='temporary_changes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
