# Generated by Django 3.2.16 on 2022-12-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0030_auto_20221228_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='intergroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
