# Generated by Django 3.2.16 on 2023-08-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0030_auto_20230816_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='temporary_changes',
            field=models.TextField(blank=True, help_text='e.g. Please note that no meeting will occure on January 1st', max_length=1000, null=True),
        ),
    ]
