# Generated by Django 3.2.16 on 2023-08-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0032_alter_meeting_temporary_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='xmas_closed',
        ),
    ]
