# Generated by Django 3.2.16 on 2023-08-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0033_remove_meeting_xmas_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='xmas_open',
        ),
    ]
