# Generated by Django 3.2.16 on 2023-08-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0034_remove_meeting_xmas_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='note_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
