# Generated by Django 3.2.16 on 2023-08-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0037_alter_meeting_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='email_confirmed',
            field=models.CharField(choices=[('CONFIRMED', 'confirmed'), ('UNCONFIRMED', 'unconfirmed'), ('PRE', 'pre')], default='PRE', max_length=50),
        ),
    ]
