##
# Clone and pull the repo
##
- name: Set up git configuration
  apt: name=git state=latest
  become: yes

- git: 
    repo: "{{ code_repository_url }}"
    dest: "{{ app_dir }}"
    force: yes
    