# Generated by Django 2.2.9 on 2020-02-21 14:03

from django.db import migrations



def update_event_types(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    RecurringEventChild = apps.get_model('event','RecurringEventChild')
    RecurringEventParent = apps.get_model('event','RecurringEventParent')
    MultiDayEvent = apps.get_model('event','MultiDayEvent')
    SingleDayEvent = apps.get_model('event','SingleDayEvent')
    event_types = ['Convention','Region','Workshop','Intergroup']
    RecurringEventChild.objects.all().update(type=4)
    RecurringEventParent.objects.all().update(type=4)
    MultiDayEvent.objects.all().update(type=4)
    SingleDayEvent.objects.all().update(type=4)

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200220_1636'),
    ]

    operations = [migrations.RunPython(update_event_types),
    ]
