# Generated by Django 2.2.9 on 2019-12-30 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191230_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringeventparent',
            name='recurring_end_date',
            field=models.DateField(default=datetime.date(2019, 12, 30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurringeventparent',
            name='recurring_start_date',
            field=models.DateField(default=datetime.date(2019, 12, 30)),
            preserve_default=False,
        ),
    ]
