# Generated by Django 2.2.9 on 2019-12-31 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('event', '0004_auto_20191230_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOffEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
                ('date', models.DateField(verbose_name='Post date')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='recurringeventchild',
            name='child_date',
        ),
        migrations.AddField(
            model_name='recurringeventchild',
            name='body',
            field=wagtail.core.fields.RichTextField(default='blah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringeventchild',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 31), verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringeventchild',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 12, 31, 17, 11, 41, 318245), verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringeventchild',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2019, 12, 31, 17, 11, 55, 107713), verbose_name='Start Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringeventparent',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 12, 31, 17, 12, 38, 170988), verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringeventparent',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2019, 12, 31, 17, 12, 41, 863349), verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
