# Generated by Django 2.2.9 on 2020-01-01 09:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('event', '0006_auto_20191231_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiDayEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
                ('start_date', models.DateField(verbose_name='Post date')),
                ('end_date', models.TimeField(verbose_name='Start Time')),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='recurringeventchild',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singledayevent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
