# Generated by Django 2.2.9 on 2020-01-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200101_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringeventchild',
            options={'ordering': ['date']},
        ),
    ]
