# Generated by Django 2.2.9 on 2020-01-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0004_genericpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='GenericPage',
        ),
        migrations.DeleteModel(
            name='StoryPage',
        ),
    ]
