# Generated by Django 2.2.9 on 2020-03-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_standardindexpage'),
    ]

    operations = [
    ]
