# Generated by Django 2.2.9 on 2020-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_linkpage_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpage',
            name='target',
            field=models.TextField(default=''),
        ),
    ]
