# Generated by Django 2.2.9 on 2020-03-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200329_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpage',
            name='target',
        ),
    ]
