# Generated by Django 2.2.9 on 2020-04-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0014_homepagenotices'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagenotices',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page', verbose_name='link to an internal page'),
        ),
    ]
