# Generated by Django 2.2.9 on 2020-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepagenotices_link_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('quotation', models.CharField(max_length=1000)),
                ('citation', models.CharField(max_length=100)),
                ('reading', models.TextField()),
            ],
        ),
    ]
