# Generated by Django 2.2.9 on 2020-11-22 09:47
import json
import os
from django.db import migrations
from django.conf import settings


""" Note: This duplicates the import used in 0017_auto_20201122_0947.

We duplicate this operation to force staging to pick up the new version of
the readings/reflections.json file.
"""


def import_reflections(apps, schema_editor):
    # We can't import the Relections model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Reflection = apps.get_model('home', 'Reflections')
    json_data = open(os.path.join(settings.BASE_DIR, 'readings/reflections.json'))
    data = json.load(json_data)
    for reading in data['daily_reflections']:
        month = reading['month']
        day = reading['day']
        title = reading['title']
        quotation = reading['quotation']
        citation = reading.get('citation','') 
        reading = reading.get('reading','')
        defaults = {'title': title, 'quotation': quotation,
                    'citation': citation, 'reading': reading}
        _, _ = Reflection.objects.update_or_create(
            month=month, day=day, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201122_0947'),
    ]
    
    operations = [
        migrations.RunPython(import_reflections),
    ]
