# Generated by Django 2.2.24 on 2021-06-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homepagevideos_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='body',
            new_name='url',
        ),
    ]
